### ISSUE TITLE
The systray relevant options still have problems.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#180]
Hi,

If I enabled the systray relevant options, the problem will happen and the corresponding settings do not take effect at all. See the log info:

```
werner@X10DAi-01:~$ pyidm 
>> Load Application setting from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-52-generic-x86_64-with-glibc2.2.5 - x86_64
>> Python version: 3.8.3 (default, May 25 2020, 15:44:25) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> Systray Gtk 3.0: No module named 'gi'
url_watchdog, new url:  https://www.pdfdrive.com/download.pdf?id=184429645&h=da54166f1afede2cb8f723f3c4fd0a8f&u=cache&ext=pdf
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 162, in _update_icon
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 389, in _assert_docked
    assert self._systray_manager
AssertionError
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 143, in _show
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 389, in _assert_docked
    assert self._systray_manager
AssertionError
```

Regards,
HY

**Comment by pyIDM** [comment]
@hongyi-zhao 
can you install GTK+3 and try again

for ubuntu: 
Open a terminal and Execute `sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-3.0`

reference: https://pygobject.readthedocs.io/en/latest/getting_started.html#ubuntu-logo-ubuntu-debian-logo-debian

**Comment by hongyi-zhao** [comment]
All these packages have been installed on my Ubuntu 20.04 box.

```
$ dpkg -l | egrep -i 'python3-gi|gir1\.2-gtk-3\.0'
ii  gir1.2-gtk-3.0:amd64                       3.24.20-0ubuntu1                    amd64        GTK graphical user interface library -- gir bindings
ii  python3-gi                                 3.36.0-1                            amd64        Python 3 bindings for gobject-introspection libraries
ii  python3-gi-cairo                           3.36.0-1                            amd64        Python 3 Cairo bindings for the GObject library

```

**Comment by pyIDM** [comment]
you might try these steps:

Installing from PyPI with pip:
Open a terminal and enter your virtual environment
Execute `sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0` to install the build dependencies and GTK
Execute `pip3 install pycairo to build and install Pycairo`
Execute `pip3 install PyGObject to build and install PyGObject`

**Comment by hongyi-zhao** [comment]
This really eliminate the error log. But when I close the PyIDM, it still doesn't minimize to systray even I've checked the corresponding option.

**Comment by pyIDM** [comment]
does it show the systray icon now?

**Comment by hongyi-zhao** [comment]
> does it show the systray icon now?

When I close it, the systray icon will disappear.

**Comment by pyIDM** [comment]
just to make sure,
does these options checked
![image](https://user-images.githubusercontent.com/58998813/97191757-dd08f700-17af-11eb-9ec1-0e0fe6b71082.png)

**Comment by pyIDM** [comment]
did you get any error messages when closing pyidm

**Comment by hongyi-zhao** [comment]
> just to make sure,
> does these options checked
> ![image](https://user-images.githubusercontent.com/58998813/97191757-dd08f700-17af-11eb-9ec1-0e0fe6b71082.png)

![image](https://user-images.githubusercontent.com/11155854/97192542-f5ded000-17e2-11eb-9336-9eae67e58d72.png)

**Comment by hongyi-zhao** [comment]
> did you get any error messages when closing pyidm

```
werner@X10DAi-01:~$ pyidm 
>> Load Application setting from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> youtube-dl version: 2020.09.20, load_time= 0 seconds
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-52-generic-x86_64-with-glibc2.2.5 - x86_64
>> Python version: 3.8.3 (default, May 25 2020, 15:44:25) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!

```

**Comment by pyIDM** [comment]
you didn't get something like below entries in terminal when close pyidm?

```
Gui terminated
Stop all downloads
>> setting saved in: /home/.../setting.cfg
>> downloads items list saved in: /home/.../downloads.dat
```

**Comment by hongyi-zhao** [comment]
```
werner@X10DAi-01:~$ pyidm 
>> Load Application setting from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> check ffmpeg availability?
>> ffmpeg checked ok! - at:  /usr/bin/ffmpeg
>> ------------------------------ PyIDM ------------------------------
>> Starting PyIDM version: 2020.10.11 Non-Frozen
>> operating system: Linux-5.4.0-52-generic-x86_64-with-glibc2.2.5 - x86_64
>> Python version: 3.8.3 (default, May 25 2020, 15:44:25) 
[GCC 9.3.0]
>> current working directory: /home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm
>> FFMPEG: /usr/bin/ffmpeg
>> controller.get_d_list()> sending d_list
>> url watchdog active!
>> youtube-dl version: 2020.09.20, load_time= 1 seconds
>> download item uid_3bb0e121d4e04ba5672fd644e4e2a427 already in list, check resume availability
>> check resuming?
>> resume is possible
>> 

>> ==========================================================================================================
>> start downloading file: "parallel_studio_xe_2020_update1_cluster_edition.tgz", size: 2.79 GB, to: /home/werner/Downloads 

>> load_progress_info()> rebuild segments from previous download for: parallel_studio_xe_2020_update1_cluster_edition.tgz
>> Thread Manager()> concurrency method: Individual Threads
>> Thread Manager: allowable connections: 2
>> Seg 0 start, size: 356.7 MB - range: [0, 374074153]  - worker 5
>> Seg 1 start, size: 356.7 MB - range: [374074154, 748148307]  - worker 6
>> Thread Manager: allowable connections: 3
>> Seg 2 start, size: 356.7 MB - range: [748148308, 1122222461]  - worker 7
>> Thread Manager: allowable connections: 4
>> Seg 3 start, size: 356.7 MB - range: [1122222462, 1496296615]- minimum speed= 20480, timeout=10  - worker 0
>> Thread Manager: allowable connections: 5
>> Seg 4 start, size: 356.7 MB - range: [1496296616, 1870370769]- minimum speed= 20480, timeout=10  - worker 1
>> Thread Manager: allowable connections: 6
>> Seg 5 start, size: 356.7 MB - range: [1870370770, 2244444923]- minimum speed= 20480, timeout=10  - worker 2
>> Thread Manager: allowable connections: 7
>> Seg 6 start, size: 356.7 MB - range: [2244444924, 2618519077]- minimum speed= 20480, timeout=10  - worker 3
>> Thread Manager: allowable connections: 8
>> Seg 7 start, size: 356.7 MB - range: [2618519078, 2992593233]- minimum speed= 20480, timeout=10  - worker 4
>> thread_manager uid_3bb0e121d4e04ba5672fd644e4e2a427: quitting
>> brain uid_3bb0e121d4e04ba5672fd644e4e2a427: Cancelled download
>> brain uid_3bb0e121d4e04ba5672fd644e4e2a427: quitting
>> ========================================================================================================== 

>> file_manager uid_3bb0e121d4e04ba5672fd644e4e2a427: quitting
^CTraceback (most recent call last):
  File "/home/werner/.pyenv/versions/pyidm/bin/pyidm", line 11, in <module>
    load_entry_point('PyIDM', 'console_scripts', 'pyidm')()
  File "/home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm/PyIDM.py", line 55, in main
    c.run()
  File "/home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm/controller.py", line 1523, in run
    self.view.run()
  File "/home/werner/Public/repo/github.com/idm-pydidm/PyIDM.git/pyidm/tkview.py", line 3100, in run
    self.root.mainloop()
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/tkinter/__init__.py", line 1420, in mainloop
    self.tk.mainloop(n)
KeyboardInterrupt

```
