### ISSUE TITLE
why update yt-dlp error

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#378]
```
start Checking for update ....
>> check for firedm latest version on pypi.org...
>> check for youtube_dl latest version on pypi.org...
>> check for yt_dlp latest version on pypi.org...
>> check for awesometkinter latest version on pypi.org...
>> done checking: firedm current: 2021.11.18 latest: 2021.11.18
>> done checking: awesometkinter current: 2021.11.8 latest: 2021.11.8
>> done checking: yt_dlp current: 2021.11.10.1 latest: 2021.12.1
>> done checking: youtube_dl current: 2021.06.06 latest: 2021.6.6
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/tmp/.mount_FireDMyotxXd/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/tmp/.mount_FireDMyotxXd/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/.mount_FireDMyotxXd/usr/src/firedm/controller.py", line 1171, in check_for_update
    if tf and not check_write_permission(tf):
  File "/tmp/.mount_FireDMyotxXd/usr/src/firedm/utils.py", line 1254, in check_write_permission
    existing_names = os.listdir(target)
FileNotFoundError: [Errno 2] No such file or directory: '/home/candra/.config/FireDM/appimage-update-folder/updated-firedm'
```
FireDM-2021.11.18-x86_64.AppImage

**Comment by firedm** [comment]
@candrapersada 
thanks for reporting this, 
this is a bug, and will be fixed in next version
as a temporary fix, you can create below folder manually and try to update again
`/home/candra/.config/FireDM/appimage-update-folder/updated-firedm`
