### ISSUE TITLE
why the download button doesn't work for playlists

### ISSUE THREAD

**Issue by candrapersada** [firedm/FireDM#379]
```
>> [youtube:tab] Downloading playlist PL8gtB5P9cW5U1IdijzJeRZvRTf_UOaiOU; add --no-playlist to just download video Fc5uw3QgWlw
>> [youtube:tab] PL8gtB5P9cW5U1IdijzJeRZvRTf_UOaiOU: Downloading webpage
>> [youtube:tab] PL8gtB5P9cW5U1IdijzJeRZvRTf_UOaiOU: Downloading webpage
>> [youtube:tab] PL8gtB5P9cW5U1IdijzJeRZvRTf_UOaiOU: Downloading API JSON with unavailable videos
>> processing playlist
>> controller> playlist ready
>> [youtube] Fc5uw3QgWlw: Downloading webpage
>> [youtube] Fc5uw3QgWlw: Downloading android player API JSON
>> [youtube] Fc5uw3QgWlw: Downloading MPD manifest
>> [youtube] Fc5uw3QgWlw: Downloading MPD manifest
Exception in Tkinter callback
Traceback (most recent call last):
  File "/tmp/.mount_FireDM2h7Q15/usr/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/tmp/.mount_FireDM2h7Q15/usr/src/firedm/tkview.py", line 2557, in download
    selected_idx = [int(x) for x in self.table.selection()]
  File "/tmp/.mount_FireDM2h7Q15/usr/src/firedm/tkview.py", line 2557, in <listcomp>
    selected_idx = [int(x) for x in self.table.selection()]
ValueError: invalid literal for int() with base 10: 'I001'
```

**Comment by firedm** [comment]
@candrapersada 

my guess you entered non number 'i001' somewhere in playlist numbers format

![image](https://user-images.githubusercontent.com/58998813/144488616-b189d0c6-6411-4203-b15c-68d1bd82282b.png)

**Comment by candrapersada** [comment]
> is this right?
 
no, the problem is with Appimage

**Comment by firedm** [comment]
> > is this right?
> 
> no, the problem is with Appimage

you're right just tested the AppImage and found the bug, will try to make a fix

**Comment by firedm** [comment]
@candrapersada 
please try the new version 2021.12.2.post1 and let me know if problem fixed

**Comment by candrapersada** [comment]
> let me know if problem fixed

yes
