### ISSUE TITLE
Customize firedm for Python 3.10

### ISSUE THREAD

**Issue by robson-66** [firedm/FireDM#395]
```
Traceback (most recent call last):
  File "/usr/bin/firedm", line 33, in <module>
    sys.exit(load_entry_point('FireDM==2021.9.28', 'console_scripts', 'firedm')())
  File "/usr/bin/firedm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/firedm/FireDM.py", line 35, in <module>
    from .tkview import MainWindow
  File "/usr/lib/python3.10/site-packages/firedm/tkview.py", line 19, in <module>
    import awesometkinter as atk
ModuleNotFoundError: No module named 'awesometkinter'
```

**Comment by Aboghazala** [comment]
@robson-66 
what is your os
how do you install/run firedm, i.e. thru pip install, or from source
did you install the requirements, e.g. awesometkinter as traceback error shows?

**Comment by robson-66** [comment]
My system is Arch Linux, and there was a Python update today, and rebuilding firedm does nothing. The result is above when running in terminal.

**Comment by Aboghazala** [comment]
try this from a terminal 
python3 -m pip install awesometkinter
and try to run firedm again and see if you get different error

or you can install all required packages by 
python3 -m pip install -r requirements.txt

and this is the [link](https://github.com/firedm/FireDM/raw/master/requirements.txt) for requirements.txt

**Comment by robson-66** [comment]
Just rebuilt `python-awesometkinter` and now `firedm` works.
