### ISSUE TITLE
installing from pip, firedm does not start 

### ISSUE THREAD

**Issue by shakakibara12** [firedm/FireDM#415]
I ran the command from the readme

`python3 -m pip install firedm --user --upgrade --no-cache`

``` 
Collecting firedm
  Downloading FireDM-2021.12.26-py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 2.1 MB/s
Requirement already satisfied: packaging in /usr/lib/python3.10/site-packages (from firedm) (20.9)
Collecting pycurl
  Downloading pycurl-7.44.1.tar.gz (227 kB)
     |████████████████████████████████| 227 kB 13.2 MB/s
Collecting Pillow>=6.0.0
  Downloading Pillow-9.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 3.5 MB/s
Requirement already satisfied: yt-dlp in ./.local/lib/python3.10/site-packages (from firedm) (2021.12.25)
Collecting plyer
  Downloading plyer-2.0.0-py2.py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 4.1 MB/s
Requirement already satisfied: distro in /usr/lib/python3.10/site-packages (from firedm) (1.6.0)
Collecting youtube-dl
  Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 27.8 MB/s
Collecting pystray
  Downloading pystray-0.19.2-py2.py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 4.5 MB/s
Collecting awesometkinter>=2021.6.4
  Downloading AwesomeTkinter-2021.11.8-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 21.6 MB/s
Collecting certifi
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 13.5 MB/s
Collecting python-bidi
  Downloading python_bidi-0.4.2-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/lib/python3.10/site-packages (from packaging->firedm) (2.4.7)
Collecting python-xlib>=0.17
  Downloading python_xlib-0.31-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 14.4 MB/s
Requirement already satisfied: six in /usr/lib/python3.10/site-packages (from pystray->firedm) (1.16.0)
Requirement already satisfied: mutagen in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (1.45.1)
Requirement already satisfied: websockets in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (10.1)
Requirement already satisfied: pycryptodomex in ./.local/lib/python3.10/site-packages (from yt-dlp->firedm) (3.12.0)
Using legacy 'setup.py install' for pycurl, since package 'wheel' is not installed.
Installing collected packages: python-xlib, python-bidi, Pillow, youtube-dl, pystray, pycurl, plyer, certifi, awesometkinter, firedm
    Running setup.py install for pycurl ... done
Successfully installed Pillow-9.0.0 awesometkinter-2021.11.8 certifi-2021.10.8 firedm-2021.12.26 plyer-2.0.0 pycurl-7.44.1 pystray-0.19.2 python-bidi-0.4.2 python-xlib-0.31 youtube-dl-2021.12.17
```

It installs Successfully but when i try to run it, i get this error:

```
<sengoku@lappy ~>$ firedm
Traceback (most recent call last):
  File "/home/sengoku/.local/bin/firedm", line 5, in <module>
    from firedm.FireDM import main
  File "/home/sengoku/.local/lib/python3.10/site-packages/firedm/FireDM.py", line 35, in <module>
    from .tkview import MainWindow
  File "/home/sengoku/.local/lib/python3.10/site-packages/firedm/tkview.py", line 17, in <module>
    import tkinter as tk
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
```
**System Information:**
```
OS: Arch Linux x86_64
Kernel: 5.15.12-zen1-1-zen
Shell: zsh 5.8
WM: sway
```
`python -V`
Python 3.10.1
`pip3 -V`
pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)

**Comment by Aboghazala** [comment]
I believe tkinter is not installed on your system
try:
`sudo pacman -S tk`

**Comment by shakakibara12** [comment]
Yes you are right! It is installed now thanks!
