### ISSUE TITLE
Failed to dock icon.

### ISSUE THREAD

**Issue by hongyi-zhao** [firedm/FireDM#96]
Hi,

I noted the following message each time when I start pyidm:

```
werner@X10DAi-01:~$ pyenv shell pyidm 
(pyidm) werner@X10DAi-01:~$ pyidm 
>> -------------------------------------------------- PyIDM --------------------------------------------------
>> Starting PyIDM version: 2020.5.18 Non-Frozen
>> operating system: Linux-5.4.0-31-generic-x86_64-with-glibc2.2.5 - x86_64
>> current working directory: /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
>> Load Application setting from /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
>> Load previous download items from /home/werner/Public/repo/github.com/pyIDM/PyIDM.git/pyidm
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 159, in _update_icon
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError
Failed to dock icon
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 140, in _show
    self._assert_docked()
  File "/home/werner/.pyenv/versions/3.8.3/envs/pyidm/lib/python3.8/site-packages/pystray/_xorg.py", line 386, in _assert_docked
    assert self._systray_manager
AssertionError
```

Any hints for solving the problem?

Regards

**Comment by pyIDM** [comment]
@hongyi-zhao 
Does the application GUI starts?, is there a systray icon?
i recently used pystray to get a systray icon, it works on windows, 
and it failed on Manjaro so i used GTK+ 3.0 to implement systray, 
didn't test it on any other distro yet
for  Ubuntu, I think pystray should use app_indicator, not sure if this problem is related to run pystray from a thread or not,
I will do more investigation to find out

**Comment by hongyi-zhao** [comment]
GUI starts without systray icon.

**Comment by hongyi-zhao** [comment]
It seems this problem is still not solved till now.

**Comment by pyIDM** [comment]
True, I didn't work on this issue yet
